
version: '3'

services:
 
  db:
    image: mysql
    command: --default-authentication-plugin=@Rocky#123.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: @Rocky#123.
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    command: python -m flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
